### ISSUE TITLE
letting the OnnxTransformer handle the conversion

### ISSUE THREAD

**Issue by adrinjalali** [xadupre/scikit-onnxruntime#3]
Right now the user seems to need to handle the conversion using the skl2onnx routines, and then pass the byte object to the transformer.

It may be a good idea to have the transformer to accept a sklearn model, and persist/cache it if necessary.

The end user would then only need to know the skonnxrt API, and it would simplify the examples.

WDYT @xadupre ?

**Comment by xadupre** [comment]
I agree. I was not sure about this project so I moved the code into a different one (https://www.xavierdupre.fr/app/mlprodict/helpsphinx/index.html) which implements the same interface OnnxTransformer as well as a python runtime for ONNX which I use to speed up the development of the converters in sklearn-onnx.
